sieste_chambre_grenier:
  alias: Sièste Chambre Grenier
  sequence:
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.volet_chambre_low_speed
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.volet_velux_chambre
  - service: climate.turn_on
    data: {}
    target:
      entity_id: climate.chambre
  - delay: '{{states(''input_datetime.ac_timer'')}}'
  - service: climate.turn_off
    data: {}
    target:
      entity_id: climate.chambre
  mode: single
  icon: mdi:sleep